
import React, { useState } from 'react';
import { 
  ArrowRight, Copy, Check, ChevronDown, ChevronUp, 
  ExternalLink, BookOpen, Users, Video, TrendingUp, Shield 
} from 'lucide-react';
import { Link } from 'react-router-dom';

const Home: React.FC = () => {
  const [copied, setCopied] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  // COLLAGE IMAGES (Add unlimited links here)
  const collageImages = [
    "https://images.unsplash.com/photo-1611974765270-ca1258634369?q=80&w=400&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=400&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=400&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1535320903710-d9cf11350062?q=80&w=400&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1642543492481-44e81e3914a7?q=80&w=400&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1526304640152-d4619684e484?q=80&w=400&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=400&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?q=80&w=400&auto=format&fit=crop"
  ];

  const handleCopy = () => {
    navigator.clipboard.writeText('G1012943001');
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const toggleFaq = (index: number) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  const faqs = [
    { q: "What are trading signals and how do they work?", a: "Trading signals are trade recommendations generated by our experts using technical analysis. We tell you the asset, direction (Buy/Sell), and timing." },
    { q: "How accurate are MegaTrades signals?", a: "Our signals are backed by rigorous market analysis, maintaining a high win rate suitable for consistent growth." },
    { q: "Where can I receive the signals?", a: "Signals are delivered instantly via our exclusive Telegram channel." },
    { q: "Do I need prior experience to use your signals?", a: "No! Our signals are beginner-friendly. We provide clear instructions on how to execute every trade." },
    { q: "What platform should I use to trade?", a: "We recommend ExpertOption for the best compatibility with our strategy." },
    { q: "How do I know when to enter a trade?", a: "Our alerts are real-time. When you receive a notification, you enter the trade immediately." },
    { q: "Can I withdraw profits easily?", a: "Yes, our recommended brokers offer fast withdrawals to bank accounts and crypto wallets." },
    { q: "What’s the best way to learn trading with MegaTrades?", a: "Join our Masterclass mentorship program for a complete A-Z guide on our strategies." }
  ];

  return (
    <>
      <style>{`
        @keyframes scroll {
          0% { transform: translateX(-50%); }
          100% { transform: translateX(0); }
        }
        .animate-scroll {
          display: flex;
          width: max-content;
          animation: scroll 40s linear infinite;
        }
        .animate-scroll:hover {
          animation-play-state: paused;
        }
      `}</style>

      {/* 1. HERO SECTION */}
      <div className="relative min-h-screen flex items-center justify-center pt-20 overflow-hidden">
        {/* Background Image Overlay */}
        <div className="absolute inset-0 z-0">
          <img 
            src="https://images.unsplash.com/photo-1611974765270-ca1258634369?q=80&w=1920&auto=format&fit=crop" 
            alt="Trading Background" 
            className="w-full h-full object-cover opacity-20"
          />
          <div className="absolute inset-0 bg-gradient-to-b from-dark-900 via-dark-900/90 to-dark-900"></div>
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 w-full text-center">
          <div className="animate-fade-in max-w-4xl mx-auto">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-secondary/10 border border-secondary/20 text-secondary text-xs font-semibold tracking-wide mb-6">
              <span className="w-2 h-2 rounded-full bg-secondary animate-pulse"></span>
              RESULTS DRIVEN TRADING
            </div>
            
            <h1 className="text-5xl md:text-7xl font-bold mb-6 leading-tight">
              Welcome to <span className="text-transparent bg-clip-text bg-gradient-to-r from-secondary to-blue-400">MegaTrades</span>
            </h1>
            
            <p className="text-lg md:text-xl text-gray-300 mb-10 leading-relaxed">
              A modern trading service focused on disciplined strategies, data-driven decisions, 
              and real, consistent results — helping traders build confidence and mastery in every market move.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link to="/services" className="px-8 py-4 bg-secondary rounded-full text-white font-bold text-lg hover:bg-blue-600 transition-all hover:scale-105 shadow-lg shadow-blue-500/25">
                View Our Services
              </Link>
            </div>
          </div>

          {/* Intro Video Player */}
          <div className="mt-16 max-w-4xl mx-auto animate-fade-in">
             <div className="glass-panel p-2 rounded-3xl relative aspect-video overflow-hidden shadow-2xl border border-white/10">
                <video 
                  controls 
                  playsInline
                  className="w-full h-full object-cover rounded-2xl"
                  poster="https://images.unsplash.com/photo-1535320903710-d9cf11350062?q=80&w=1600"
                >
                  {/* IMPORTANT: Ensure 'uploads' folder is inside 'public' directory */}
                  <source src="/uploads/intro.mp4" type="video/mp4" />
                  Your browser does not support the video tag.
                </video>
             </div>
             <p className="text-sm text-gray-400 mt-4">Intro to Trading: Watch how we navigate the markets daily.</p>
          </div>
        </div>
      </div>

      {/* 2. AUTO-PLAYING IMAGE COLLAGE (MARQUEE) - Moves Left to Right */}
      <div className="py-0 bg-dark-950 border-y border-white/5 overflow-hidden">
        <div className="relative w-full">
          <div className="animate-scroll flex gap-0">
             {/* Duplicate the array to create seamless loop with no gaps */}
             {[...collageImages, ...collageImages, ...collageImages].map((img, index) => (
                <div key={index} className="w-[300px] h-[200px] flex-shrink-0 relative group">
                   <img 
                     src={img} 
                     alt={`Gallery ${index}`} 
                     className="w-full h-full object-cover grayscale group-hover:grayscale-0 transition-all duration-500 border-r border-dark-900"
                   />
                   <div className="absolute inset-0 bg-blue-600/10 opacity-0 group-hover:opacity-100 transition-opacity"></div>
                </div>
             ))}
          </div>
        </div>
      </div>

      {/* 3. HOW WE OPERATE */}
      <div id="services" className="py-20 bg-dark-900">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <h2 className="text-3xl font-bold mb-6">How We Operate</h2>
          <p className="text-xl text-gray-300 leading-relaxed glass-panel p-8 rounded-2xl">
            We offer <span className="text-secondary font-bold">free trading signals</span> on our Telegram channel — we’re one of the best signal providers in the market. We also offer a <span className="text-secondary font-bold">Masterclass</span> for individuals who are ready to learn and grow in the trading space.
          </p>
        </div>
      </div>

      {/* 4. HOW TO GET STARTED */}
      <div className="py-24 relative overflow-hidden">
        {/* Abstract Background */}
        <div className="absolute top-1/2 right-0 w-[500px] h-[500px] bg-blue-600/5 rounded-full blur-[120px] -z-10"></div>

        <div className="max-w-6xl mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">How to Get Started</h2>
            <p className="text-gray-400">Three simple steps to start your profitable journey.</p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {/* Step 1 */}
            <div className="glass-panel p-8 rounded-2xl relative border-t-4 border-secondary hover:-translate-y-2 transition-transform duration-300">
              <div className="absolute -top-5 left-1/2 transform -translate-x-1/2 w-10 h-10 bg-secondary rounded-full flex items-center justify-center font-bold text-white text-lg shadow-lg">1</div>
              <h3 className="text-xl font-bold mt-4 mb-4 text-center">Register Account</h3>
              <p className="text-gray-400 text-sm text-center mb-6">
                Click below to register on ExpertOption. Use our promo code to get <span className="text-white font-bold">120% bonus</span> on your first deposit.
              </p>
              
              <div className="bg-dark-950 p-4 rounded-xl mb-6 border border-white/5 text-center">
                <span className="text-xs text-gray-500 uppercase tracking-wide">Promo Code</span>
                <div className="flex items-center justify-between mt-2 bg-dark-800 p-2 rounded-lg">
                  <code className="text-secondary font-mono font-bold text-lg pl-2">G1012943001</code>
                  <button 
                    onClick={handleCopy}
                    className="p-2 bg-white/10 hover:bg-white/20 rounded-md transition-colors"
                    title="Copy Code"
                  >
                    {copied ? <Check size={18} className="text-green-400" /> : <Copy size={18} />}
                  </button>
                </div>
              </div>

              <a 
                href="https://r.shortlify.com/?prefid=1012943001&ptr=TG" 
                target="_blank" 
                rel="noreferrer"
                className="w-full flex items-center justify-center gap-2 bg-secondary hover:bg-blue-600 py-3 rounded-xl font-bold text-white transition-all"
              >
                Register Now <ExternalLink size={16} />
              </a>
            </div>

            {/* Step 2 */}
            <div className="glass-panel p-8 rounded-2xl relative border-t-4 border-purple-500 hover:-translate-y-2 transition-transform duration-300">
              <div className="absolute -top-5 left-1/2 transform -translate-x-1/2 w-10 h-10 bg-purple-500 rounded-full flex items-center justify-center font-bold text-white text-lg shadow-lg">2</div>
              <h3 className="text-xl font-bold mt-4 mb-4 text-center">Complete Setup</h3>
              <p className="text-gray-400 text-sm text-center mb-8">
                Click the register button in the top right corner of the page and fill in the required form details securely.
              </p>
              <div className="h-24 flex items-center justify-center">
                 <Users className="w-16 h-16 text-purple-500/50" />
              </div>
            </div>

            {/* Step 3 */}
            <div className="glass-panel p-8 rounded-2xl relative border-t-4 border-green-500 hover:-translate-y-2 transition-transform duration-300">
              <div className="absolute -top-5 left-1/2 transform -translate-x-1/2 w-10 h-10 bg-green-500 rounded-full flex items-center justify-center font-bold text-white text-lg shadow-lg">3</div>
              <h3 className="text-xl font-bold mt-4 mb-4 text-center">Activate & Trade</h3>
              <p className="text-gray-400 text-sm text-center mb-8">
                Confirm your email to activate your account. Start today, and by tomorrow you'll be analyzing markets!
              </p>
              <div className="flex justify-center text-green-400 font-bold gap-2 items-center">
                 <TrendingUp /> Start Profiting
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* 5. WHY TRADE WITH US & WHAT WE OFFER */}
      <div className="bg-dark-800 py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-2 gap-16 items-center">
            <div>
              <h2 className="text-3xl font-bold mb-6">Why Trade With Us</h2>
              <div className="space-y-6">
                {[
                  "Experienced trading team with proven track record",
                  "Risk-managed strategies to protect capital",
                  "Fast withdrawals & transparent reporting",
                  "Real-time support and community access"
                ].map((item, idx) => (
                  <div key={idx} className="flex items-center gap-4 glass-panel p-4 rounded-xl hover:bg-white/5 transition-colors">
                    <div className="w-8 h-8 rounded-full bg-green-500/20 flex items-center justify-center shrink-0">
                      <Check size={16} className="text-green-400" />
                    </div>
                    <span className="text-lg text-gray-200">{item}</span>
                  </div>
                ))}
              </div>
            </div>
            
            <div className="glass-panel p-8 rounded-3xl border border-white/5">
              <h3 className="text-2xl font-bold mb-4 text-secondary">What We Offer</h3>
              <p className="text-gray-400 mb-8 leading-relaxed">
                Trading tools for beginners, premium signal services, and educational resources tailored for both beginners and professional traders. We bridge the gap between learning and earning.
              </p>
              <div className="grid grid-cols-2 gap-4">
                 {/* Signals Button - Linked to Telegram */}
                 <a 
                   href="https://t.me/greatmega_eo" 
                   target="_blank" 
                   rel="noreferrer" 
                   className="bg-dark-900 p-4 rounded-xl text-center group hover:bg-secondary transition-all cursor-pointer border border-white/5 hover:border-transparent"
                 >
                    <Shield className="w-8 h-8 mx-auto text-blue-400 mb-2 group-hover:text-white transition-colors" />
                    <span className="font-bold text-sm block group-hover:text-white">Signals</span>
                    <span className="text-[10px] text-gray-500 group-hover:text-white/80">Click to Join</span>
                 </a>

                 {/* Education Button - Linked to eBook */}
                 <Link 
                   to="/ebook"
                   className="bg-dark-900 p-4 rounded-xl text-center group hover:bg-purple-600 transition-all cursor-pointer border border-white/5 hover:border-transparent"
                 >
                    <BookOpen className="w-8 h-8 mx-auto text-purple-400 mb-2 group-hover:text-white transition-colors" />
                    <span className="font-bold text-sm block group-hover:text-white">Education</span>
                    <span className="text-[10px] text-gray-500 group-hover:text-white/80">Get the eBook</span>
                 </Link>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* 6. EBOOK & RESOURCES */}
      <div className="py-24 max-w-7xl mx-auto px-4">
        <div className="glass-panel rounded-3xl overflow-hidden hover:shadow-2xl hover:shadow-purple-500/10 transition-all">
          <div className="grid md:grid-cols-2">
            <div className="p-12 flex flex-col justify-center">
              <div className="inline-block px-3 py-1 rounded bg-purple-500/20 text-purple-400 text-xs font-bold w-fit mb-4">BEST SELLER</div>
              <h2 className="text-3xl md:text-4xl font-bold mb-6">Get My Trading eBook Strategy</h2>
              <p className="text-gray-400 mb-8 leading-relaxed">
                Unlock the secrets to market structure and psychology. My eBook covers the exact strategies I use to navigate the markets profitably every single day.
              </p>
              <Link to="/ebook" className="inline-flex items-center gap-2 px-8 py-4 bg-white text-dark-900 font-bold rounded-xl hover:bg-gray-200 transition-colors w-fit">
                Get the eBook <BookOpen size={20} />
              </Link>
            </div>
            <div className="relative h-64 md:h-auto bg-dark-800">
               <img 
                 src="https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1000&auto=format&fit=crop" 
                 alt="eBook Cover" 
                 className="w-full h-full object-cover opacity-80"
               />
               <div className="absolute inset-0 bg-gradient-to-r from-dark-900/90 to-transparent md:bg-gradient-to-l"></div>
            </div>
          </div>
        </div>
      </div>

      {/* 7. MASTERCLASS & LIVE TRADING */}
      <div className="bg-dark-950 py-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
             <h2 className="text-4xl font-bold mb-4">Ready to Level Up?</h2>
             <p className="text-gray-400">Join exclusive programs designed for serious traders.</p>
          </div>

          <div className="space-y-20">
            {/* Live Trading */}
            <div className="grid md:grid-cols-2 gap-12 items-center">
               <div className="order-2 md:order-1">
                  <div className="w-12 h-12 bg-red-500/20 rounded-xl flex items-center justify-center mb-6">
                     <Video className="text-red-500" />
                  </div>
                  <h3 className="text-3xl font-bold mb-4">Live Trading Session</h3>
                  <p className="text-gray-400 leading-relaxed mb-6">
                    Experience the market in real time with our Live Trading Sessions. Watch our experts analyze charts, execute trades, and explain their decisions as they happen. It’s the fastest way to learn practical skills.
                  </p>
                  <Link to="/services" className="text-secondary font-bold hover:underline flex items-center gap-1">
                     Join Next Session <ArrowRight size={16} />
                  </Link>
               </div>
               <div className="order-1 md:order-2">
                  <div className="glass-panel p-2 rounded-2xl">
                     <img src="https://images.unsplash.com/photo-1611974765270-ca1258634369?q=80&w=800&auto=format&fit=crop" className="rounded-xl w-full" alt="Live Trading" />
                  </div>
               </div>
            </div>

            {/* Masterclass Mentorship */}
            <div className="grid md:grid-cols-2 gap-12 items-center">
               <div>
                  <div className="glass-panel p-2 rounded-2xl">
                     <img src="https://images.unsplash.com/photo-1524178232363-1fb2b075b955?q=80&w=800&auto=format&fit=crop" className="rounded-xl w-full" alt="Mentorship" />
                  </div>
               </div>
               <div>
                  <div className="w-12 h-12 bg-secondary/20 rounded-xl flex items-center justify-center mb-6">
                     <Users className="text-secondary" />
                  </div>
                  <h3 className="text-3xl font-bold mb-4">Masterclass Mentorship</h3>
                  <p className="text-gray-400 leading-relaxed mb-6">
                    Our Masterclass is more than just lessons — it’s a mentorship experience. You’ll learn directly from seasoned traders who walk you through proven strategies, mindset development, and risk management.
                  </p>
                  <Link to="/ebook" className="px-8 py-3 bg-secondary rounded-full text-white font-bold hover:shadow-lg hover:shadow-blue-500/20 transition-all">
                     Join the Masterclass
                  </Link>
               </div>
            </div>

             {/* Community Meetup */}
             <div className="glass-panel p-8 md:p-12 rounded-3xl text-center relative overflow-hidden">
                <div className="absolute top-0 left-0 w-full h-full z-0">
                    <img src="https://images.unsplash.com/photo-1515187029135-18ee286d815b?q=80&w=1000&auto=format&fit=crop" className="w-full h-full object-cover opacity-10" alt="Community" />
                </div>
                <div className="relative z-10">
                    <h3 className="text-3xl font-bold mb-4">Community Meetup</h3>
                    <p className="text-gray-400 max-w-2xl mx-auto mb-8">
                        MegaTrades isn’t just a trading service — it’s a growing community. Our meetups bring members together to share insights, build connections, and learn from each other in real time.
                    </p>
                    <button className="text-white border border-white/20 hover:bg-white/5 px-6 py-2 rounded-full transition-all">
                        View Upcoming Events
                    </button>
                </div>
             </div>
          </div>
        </div>
      </div>

      {/* 8. FAQ SECTION */}
      <div className="py-24 bg-dark-900">
        <div className="max-w-3xl mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-2">Frequently Asked Questions</h2>
            <p className="text-gray-500">Everything you need to know about MegaTrades.</p>
          </div>

          <div className="space-y-4">
            {faqs.map((item, index) => (
              <div key={index} className="glass-panel rounded-xl overflow-hidden transition-all duration-300">
                <button 
                  onClick={() => toggleFaq(index)}
                  className="w-full px-6 py-4 flex items-center justify-between text-left hover:bg-white/5 transition-colors"
                >
                  <span className="font-semibold text-gray-200">{item.q}</span>
                  {openFaq === index ? <ChevronUp className="text-secondary" /> : <ChevronDown className="text-gray-500" />}
                </button>
                <div 
                  className={`px-6 text-gray-400 leading-relaxed overflow-hidden transition-all duration-300 ${openFaq === index ? 'max-h-40 py-4 border-t border-white/5' : 'max-h-0'}`}
                >
                  {item.a}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* 9. FOOTER CTA */}
      <div className="py-20 bg-gradient-to-br from-secondary to-blue-800 text-center px-4">
         <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">Let's Trade & Grow Together!</h2>
         <p className="text-blue-100 text-lg mb-8 max-w-xl mx-auto">
             Join the fastest growing community of profitable traders today.
         </p>
         <Link to="/register" className="inline-block px-10 py-4 bg-white text-blue-600 font-bold text-xl rounded-full hover:shadow-2xl hover:scale-105 transition-all">
             Start Now
         </Link>
      </div>
    </>
  );
};

export default Home;
